name: tracker

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  update: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: umgefahren/hackathon-action@v1.3
        with:
          issue_number: 1
          hackathon_end: "10/16/2022 16:00:00"
          my_token: ${{ secrets.GITHUB_TOKEN }}